name: Run CI

on: [push]

env:
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
  BUNDLE_PATH: vendor/bundle
  RAILS_ENV: test
  PGHOST: localhost
  PGUSER: postgres
  POSTGRES_PASSWORD: postgres
  CI_ENV: true
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: satackey/action-docker-layer-caching
      continue-on-error: true

    - name: Run tests
      run: |
        ./test.sh